// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ifraixedes/go-ms-http-nsq-example/zombie-driver (interfaces: Service)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// Service is a mock of Service interface
type Service struct {
	ctrl     *gomock.Controller
	recorder *ServiceMockRecorder
}

// ServiceMockRecorder is the mock recorder for Service
type ServiceMockRecorder struct {
	mock *Service
}

// NewService creates a new mock instance
func NewService(ctrl *gomock.Controller) *Service {
	mock := &Service{ctrl: ctrl}
	mock.recorder = &ServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Service) EXPECT() *ServiceMockRecorder {
	return m.recorder
}

// IsZombie mocks base method
func (m *Service) IsZombie(arg0 context.Context, arg1 uint64) (bool, error) {
	ret := m.ctrl.Call(m, "IsZombie", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsZombie indicates an expected call of IsZombie
func (mr *ServiceMockRecorder) IsZombie(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsZombie", reflect.TypeOf((*Service)(nil).IsZombie), arg0, arg1)
}
